# Generated by Django 4.1 on 2022-08-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMetadata',
            fields=[
                ('GameId', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('MapName', models.TextField()),
            ],
        ),
    ]
