# Generated by Django 4.1 on 2022-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0010_alter_gameplayerlist_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlemap',
            name='map_data',
        ),
        migrations.RemoveField(
            model_name='battlemap',
            name='reference_str',
        ),
        migrations.AddField(
            model_name='battlemap',
            name='map_data_or_str_reference',
            field=models.CharField(default='Bean Island', max_length=2000),
            preserve_default=False,
        ),
    ]
