# Generated by Django 4.1.1 on 2022-09-09 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_standard_map_library', models.BooleanField()),
                ('map_name', models.CharField(max_length=64)),
                ('author_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_over', models.BooleanField(default=False)),
                ('winning_player_num', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('fog_of_war', models.BooleanField(default=False)),
                ('starting_funds', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.battlemap')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.PositiveSmallIntegerField()),
                ('co_id', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gamemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_ordinal', models.PositiveIntegerField()),
                ('action_ordinal', models.PositiveIntegerField()),
                ('player_num', models.PositiveSmallIntegerField()),
                ('command_data', models.CharField(max_length=200)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gamemetadata')),
            ],
            options={
                'ordering': ['game_id', 'turn_ordinal', 'action_ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameplayerlist',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_num'), name='PlayerId'),
        ),
        migrations.AddConstraint(
            model_name='gameaction',
            constraint=models.UniqueConstraint(fields=('game_id', 'turn_ordinal', 'action_ordinal'), name='Ordinal'),
        ),
    ]
