# Generated by Django 4.1 on 2022-08-31 23:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamemetadata',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='gamemetadata',
            name='GameId',
        ),
        migrations.RemoveField(
            model_name='gamemetadata',
            name='MapName',
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GamePlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player#', models.PositiveSmallIntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameData.gamemetadata')),
                ('player_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='map_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GameData.battlemap'),
            preserve_default=False,
        ),
    ]
