# Generated by Django 4.1 on 2022-09-01 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0002_battlemap_alter_gamemetadata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemetadata',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
