# Generated by Django 4.1 on 2022-09-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0005_gamemetadata_fog_of_war_gamemetadata_starting_funds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameaction',
            old_name='cmd_data',
            new_name='command_data',
        ),
    ]
