# Generated by Django 4.1 on 2022-09-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0006_rename_cmd_data_gameaction_command_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameaction',
            old_name='Player#',
            new_name='player_num',
        ),
        migrations.RenameField(
            model_name='gameplayerlist',
            old_name='Player#',
            new_name='player_num',
        ),
        migrations.AddConstraint(
            model_name='gameplayerlist',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_num'), name='PlayerId'),
        ),
    ]
