# Generated by Django 4.1 on 2022-09-02 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameData', '0007_rename_player#_gameaction_player_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlemap',
            name='author',
        ),
        migrations.AddField(
            model_name='battlemap',
            name='author_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battlemap',
            name='in_standard_map_library',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlemap',
            name='map_data',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='battlemap',
            name='reference_str',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='winning_player_num',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
