# Generated by Django 4.1 on 2022-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0008_remove_battlemap_author_battlemap_author_account_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameaction',
            constraint=models.UniqueConstraint(fields=('game_id', 'turn_ordinal', 'action_ordinal'), name='Ordinal'),
        ),
    ]
