# Generated by Django 4.1 on 2022-09-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0011_remove_battlemap_map_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlemap',
            name='map_data_or_str_reference',
        ),
        migrations.AddField(
            model_name='battlemap',
            name='map_name',
            field=models.CharField(default='Bean Island', max_length=64),
            preserve_default=False,
        ),
    ]
