# Generated by Django 4.1 on 2022-09-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameData', '0012_remove_battlemap_map_data_or_str_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetadata',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
